=== karzhouAndrew/JavaRepository/zolotuho/src/garden/xmlFiles/in/garden.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.it-academy.by"
           xmlns="http://www.it-academy.by"
           elementFormDefault="qualified">
    <xs:element name="plants">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tree" type="treeType" minOccurs="0" maxOccurs="5000"/>
                <xs:element name="bush" type="bushType" minOccurs="0" maxOccurs="5000"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="bushType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="age" type="xs:integer"/>
            <xs:element name="height" type="xs:integer"/>
            <xs:element name="trunkQuantity" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="treeType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="age" type="xs:integer"/>
            <xs:element name="height" type="xs:integer"/>
            <xs:element name="trunkWidth" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== karzhouAndrew/JavaRepository/zolotuho/src/garden/xmlFiles/in/garden.xml
<?xml version="1.0" encoding="UTF-8"?>
<plants xmlns="http://www.it-academy.by"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.it-academy.by garden.xsd">
    <tree>
        <name>maple</name>
        <age>100</age>
        <height>40</height>
        <trunkWidth>50</trunkWidth>
    </tree>
    <tree>
        <name>appleTree</name>
        <age>12</age>
        <height>6</height>
        <trunkWidth>30</trunkWidth>
    </tree>
    <tree>
        <name>birch</name>
        <age>15</age>
        <height>15</height>
        <trunkWidth>17</trunkWidth>
    </tree>
    <bush>
        <name>lilac</name>
        <age>3</age>
        <height>1</height>
        <trunkQuantity>12</trunkQuantity>
    </bush>
    <bush>
        <name>currant</name>
        <age>5</age>
        <height>1</height>
        <trunkQuantity>25</trunkQuantity>
    </bush>
</plants>
