=== karzhouAndrew/JavaRepository/Skrebunov/src/lab6JD2/pl.xsd
<?xml version="1.0"?>
<xs:schema xmlns="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.it-academy.by"
           xmlns:xs="http://www.it-academy.by"
           elementFormDefault="qualified">
    <xs:element name='pointsList'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name='point' type='pointType' minOccurs='0' maxOccurs='unbounded' />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="pointType">
        <xs:sequence>
            <xs:element name="x" type="xs:positiveInteger"/>
            <xs:element name="y" type="xs:positiveInteger"/>
        </xs:sequence>
        <xs:attribute name='unit' type='xs:string'/>
    </xs:complexType>
</xs:schema>

=== karzhouAndrew/JavaRepository/Skrebunov/src/lab6JD2/pl.xml
<?xml version="1.0" encoding="UTF-8"?>

<pointsList
        xmlns="http://www.it-academy.by"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.it-academy.by pl.xsd">
    <point unit="cm">
        <x>2</x>
        <y>3</y>
    </point>
    <point unit="mm">
        <x>9</x>
        <y>3</y>
    </point>
    <point unit="px">
        <x>5</x>
        <y>6</y>
    </point>
</pointsList>
