=== karzhouAndrew/JavaRepository/apetsenak/src/lab456jd2/point.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           elementFormDefault="qualified">
    <xs:element name="pointList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="point" minOccurs="0" maxOccurs="unbounded" type="Point"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Point">
        <xs:sequence>
            <xs:element name="x" type="xs:integer"/>
            <xs:element name="y" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="units" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="mm|sm|px"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== karzhouAndrew/JavaRepository/apetsenak/src/lab456jd2/point.xml
<?xml version="1.0" encoding="UTF-8"?>
<pointList xmlns="http://www.w3schools.com"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.w3schools.com point.xsd">
    <point units="sm">
        <x>10</x>
        <y>20</y>
    </point>
    <point units="mm">
        <x>3</x>
        <y>5</y>
    </point>
    <point units="px">
        <x>600</x>
        <y>500</y>
    </point>
</pointList>
