=== karzhouAndrew/JavaRepository/Boris/src/module2/laba7/other/PointList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.it-academy.by"
           xmlns="http://www.it-academy.by"
           elementFormDefault="qualified">
    <xs:element name="pointlist">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="point" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="x" type="xs:integer"/>
                            <xs:element name="y" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="units" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="px|mm|cm"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
        <!-- Для xml, сделанного в предыдущем задании, создайте схему с жестко заданными
        значениями параметра units тега point -->

=== karzhouAndrew/JavaRepository/Boris/src/module2/laba9/PointListXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<pointlist xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.it-academy.by"
           xs:schemaLocation="http://www.it-academy.by PointList.xsd">
    <point units="cm">
        <x>2</x>
        <y>3</y>
    </point>
    <point units="mm">
        <x>9</x>
        <y>3</y>
    </point>
    <point units="px">
        <x>10</x>
        <y>0</y>
    </point>
</pointlist>

        <!-- Сделайте XML на основе приведенного примера, у которого тег point будет иметь
                параметр unit — единицы измерения. Возможные значения — cm,mm,px.-->
