=== karzhouAndrew/JavaRepository/Skrebunov/src/lab5JD2/pl.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT pointsList (point*)>
        <!ATTLIST point units (cm|mm|px) #REQUIRED>
        <!ELEMENT point (x,y)>
        <!ELEMENT x (#PCDATA)>
        <!ELEMENT y (#PCDATA)>

=== karzhouAndrew/JavaRepository/Skrebunov/src/lab5JD2/pl.xml
<?xml version = "1.0"?>
<!DOCTYPE pointsList SYSTEM "pl.dtd">

<pointsList>
    <point units = "cm">
        <x>2</x>
        <y>3</y>
    </point>
    <point units = "mm">
        <x>9</x>
        <y>3</y>
    </point>
    <point units = "px">
        <x>5</x>
        <y>6</y>
    </point>
</pointsList>
