=== karzhouAndrew/JavaRepository/Shaplyko/src/add11/garden.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="plant">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tree" minOccurs="2" maxOccurs="100">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:double" name="height"/>
                            <xs:element type="xs:int" name="age"/>
                            <xs:element type="xs:double" name="speedGrow"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="bush" minOccurs="2" maxOccurs="100">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:double" name="height"/>
                            <xs:element type="xs:int" name="age"/>
                            <xs:element type="xs:double" name="speedGrow"/>
                            <xs:element type="xs:int" name="numberTrunk"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== karzhouAndrew/JavaRepository/Shaplyko/src/add11/garden.xml
<plant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="garden.xsd">
    <tree>
        <name>Береза</name>
        <height>1</height>
        <age>1</age>
        <speedGrow>0.2</speedGrow>
    </tree>
    <tree>
        <name>Каштан</name>
        <height>1.25</height>
        <age>2</age>
        <speedGrow>0.2</speedGrow>
    </tree>
    <tree>
        <name>Каштан</name>
        <height>1.5</height>
        <age>3</age>
        <speedGrow>0.2</speedGrow>
    </tree>
    <tree>
        <name>Вишня</name>
        <height>1.1</height>
        <age>2</age>
        <speedGrow>0.3</speedGrow>
    </tree>
    <tree>
        <name>Черешня</name>
        <height>0.5</height>
        <age>1</age>
        <speedGrow>0.2</speedGrow>
    </tree>
    <tree>
        <name>Слива</name>
        <height>1.2</height>
        <age>2</age>
        <speedGrow>0.2</speedGrow>
    </tree>
    <tree>
        <name>Черешня</name>
        <height>1.9</height>
        <age>3</age>
        <speedGrow>0.2</speedGrow>
    </tree>
    <tree>
        <name>Слива</name>
        <height>1</height>
        <age>2</age>
        <speedGrow>0.2</speedGrow>
    </tree>

    <bush>
        <name>Ежевика</name>
        <height>0.5</height>
        <age>3</age>
        <speedGrow>0.5</speedGrow>
        <numberTrunk>2</numberTrunk>
    </bush>
    <bush>
        <name>Крыжовник</name>
        <height>0.45</height>
        <age>2</age>
        <speedGrow>0.15</speedGrow>
        <numberTrunk>4</numberTrunk>
    </bush>
    <bush>
        <name>Смородина</name>
        <height>0.75</height>
        <age>3</age>
        <speedGrow>0.2</speedGrow>
        <numberTrunk>3</numberTrunk>
    </bush>
    <bush>
        <name>Малина</name>
        <height>0.5</height>
        <age>3</age>
        <speedGrow>0.2</speedGrow>
        <numberTrunk>1</numberTrunk>
    </bush>
</plant>
