=== karzhouAndrew/JavaRepository/Boris/src/module2/laba4_6/PointList.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT PointList (point+)>
        <!ELEMENT point (x, y)>
        <!ATTLIST point units (cm|mm|px) #REQUIRED>
        <!ELEMENT x (#PCDATA)>
        <!ELEMENT y (#PCDATA)>

        <!--  Для xml, сделанного в предыдущем задании, создайте DTD с жестко заданными
        значениями параметра units тега point -->

=== karzhouAndrew/JavaRepository/Boris/src/module2/laba4_6/PointListDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PointList SYSTEM "PointList.dtd">
<PointList>
    <point units="cm">
        <x>2</x>
        <y>3</y>
    </point>
    <point units="mm">
        <x>9</x>
        <y>3</y>
    </point>
    <point units="px">
        <x>10</x>
        <y>0</y>
    </point>
</PointList>

        <!-- Сделайте XML на основе приведенного примера, у которого тег point будет иметь
                параметр unit — единицы измерения. Возможные значения — cm,mm,px.-->
