=== karzhouAndrew/JavaRepository/Dudinsky/src/jd02park/plantsListScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.it-academy.by"
           xmlns="http://www.it-academy.by"
           elementFormDefault="qualified">
    <xs:element name="plantsList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tree" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="kind">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Birch"/>
                                        <xs:enumeration value="Maple"/>
                                        <xs:enumeration value="Oak"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="height" type="heightType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="shrub" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="kind">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Brier"/>
                                        <xs:enumeration value="Jasmine"/>
                                        <xs:enumeration value="Lilac"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="height" type="heightType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="totalTransplantData">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="overallQuantity" type="xs:nonNegativeInteger"/>
                            <xs:element name="summaryHeight" type="heightType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="heightType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== karzhouAndrew/JavaRepository/Dudinsky/src/jd02park/resultPlantsList.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<it:plantsList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.it-academy.by plantsListScheme.xsd" xmlns:it="http://www.it-academy.by">
    <it:tree>
        <it:kind>Birch</it:kind>
        <it:height>1.88</it:height>
    </it:tree>
    <it:tree>
        <it:kind>Oak</it:kind>
        <it:height>1.87</it:height>
    </it:tree>
    <it:tree>
        <it:kind>Birch</it:kind>
        <it:height>1.66</it:height>
    </it:tree>
    <it:tree>
        <it:kind>Maple</it:kind>
        <it:height>1.68</it:height>
    </it:tree>
    <it:tree>
        <it:kind>Maple</it:kind>
        <it:height>1.61</it:height>
    </it:tree>
    <it:tree>
        <it:kind>Oak</it:kind>
        <it:height>1.33</it:height>
    </it:tree>
    <it:shrub>
        <it:kind>Jasmine</it:kind>
        <it:height>1.24</it:height>
    </it:shrub>
    <it:shrub>
        <it:kind>Brier</it:kind>
        <it:height>0.97</it:height>
    </it:shrub>
    <it:shrub>
        <it:kind>Jasmine</it:kind>
        <it:height>1.17</it:height>
    </it:shrub>
    <it:shrub>
        <it:kind>Lilac</it:kind>
        <it:height>1.04</it:height>
    </it:shrub>
    <it:shrub>
        <it:kind>Brier</it:kind>
        <it:height>1.22</it:height>
    </it:shrub>
    <it:shrub>
        <it:kind>Lilac</it:kind>
        <it:height>1.19</it:height>
    </it:shrub>
    <it:totalTransplantData>
        <it:overallQuantity>12</it:overallQuantity>
        <it:summaryHeight>16.86</it:summaryHeight>
    </it:totalTransplantData>
</it:plantsList>
